"""
Tests for matching module.

Generated By: Claude Code (Claude Sonnet 4.5)
"""

from unittest.mock import patch

from ap_move_lights_to_data import matching, config


class TestFindMatchingDarks:
    """Tests for find_matching_darks function."""

    def test_matches_on_camera_settings(self):
        """Verify darks are matched on camera settings."""
        light_metadata = {
            config.KEYWORD_CAMERA: "ASI2600MM",
            config.KEYWORD_SETTEMP: "-10",
            config.KEYWORD_GAIN: "100",
            config.KEYWORD_OFFSET: "50",
            config.KEYWORD_READOUTMODE: "0",
            config.KEYWORD_EXPOSURESECONDS: "300",
        }

        dark_frames = {
            "/path/dark1.fits": {
                config.KEYWORD_CAMERA: "ASI2600MM",
                config.KEYWORD_SETTEMP: "-10",
                config.KEYWORD_GAIN: "100",
                config.KEYWORD_OFFSET: "50",
                config.KEYWORD_READOUTMODE: "0",
                config.KEYWORD_EXPOSURESECONDS: "300",
            },
            "/path/dark2.fits": {
                config.KEYWORD_CAMERA: "ASI2600MM",
                config.KEYWORD_SETTEMP: "-10",
                config.KEYWORD_GAIN: "100",
                config.KEYWORD_OFFSET: "50",
                config.KEYWORD_READOUTMODE: "0",
                config.KEYWORD_EXPOSURESECONDS: "120",  # Different exposure
            },
        }

        result, exposure_matches = matching.find_matching_darks(
            light_metadata, dark_frames
        )

        assert len(result) == 2
        assert "/path/dark1.fits" in result
        assert "/path/dark2.fits" in result

    def test_exposure_matches_true_when_same(self):
        """Verify exposure_matches is True when dark has same exposure."""
        light_metadata = {
            config.KEYWORD_CAMERA: "ASI2600MM",
            config.KEYWORD_EXPOSURESECONDS: "300",
        }

        dark_frames = {
            "/path/dark1.fits": {
                config.KEYWORD_CAMERA: "ASI2600MM",
                config.KEYWORD_EXPOSURESECONDS: "300",
            },
        }

        _, exposure_matches = matching.find_matching_darks(light_metadata, dark_frames)

        assert exposure_matches is True

    def test_exposure_matches_false_when_different(self):
        """Verify exposure_matches is False when dark has different exposure."""
        light_metadata = {
            config.KEYWORD_CAMERA: "ASI2600MM",
            config.KEYWORD_EXPOSURESECONDS: "300",
        }

        dark_frames = {
            "/path/dark1.fits": {
                config.KEYWORD_CAMERA: "ASI2600MM",
                config.KEYWORD_EXPOSURESECONDS: "120",
            },
        }

        _, exposure_matches = matching.find_matching_darks(light_metadata, dark_frames)

        assert exposure_matches is False

    def test_excludes_non_matching_camera(self):
        """Verify darks with different camera are excluded."""
        light_metadata = {
            config.KEYWORD_CAMERA: "ASI2600MM",
        }

        dark_frames = {
            "/path/dark1.fits": {
                config.KEYWORD_CAMERA: "ASI294MM",  # Different camera
            },
        }

        result, _ = matching.find_matching_darks(light_metadata, dark_frames)

        assert len(result) == 0


class TestFindMatchingFlats:
    """Tests for find_matching_flats function."""

    def test_includes_filter_in_match(self):
        """Verify flats are matched including filter."""
        light_metadata = {
            config.KEYWORD_CAMERA: "ASI2600MM",
            config.KEYWORD_FILTER: "Ha",
        }

        flat_frames = {
            "/path/flat1.fits": {
                config.KEYWORD_CAMERA: "ASI2600MM",
                config.KEYWORD_FILTER: "Ha",
            },
            "/path/flat2.fits": {
                config.KEYWORD_CAMERA: "ASI2600MM",
                config.KEYWORD_FILTER: "OIII",  # Different filter
            },
        }

        result = matching.find_matching_flats(light_metadata, flat_frames)

        assert len(result) == 1
        assert "/path/flat1.fits" in result


class TestFindMatchingBias:
    """Tests for find_matching_bias function."""

    def test_matches_on_camera_settings(self):
        """Verify bias frames are matched on camera settings."""
        light_metadata = {
            config.KEYWORD_CAMERA: "ASI2600MM",
            config.KEYWORD_SETTEMP: "-10",
            config.KEYWORD_GAIN: "100",
            config.KEYWORD_OFFSET: "50",
            config.KEYWORD_READOUTMODE: "0",
        }

        bias_frames = {
            "/path/bias1.fits": {
                config.KEYWORD_CAMERA: "ASI2600MM",
                config.KEYWORD_SETTEMP: "-10",
                config.KEYWORD_GAIN: "100",
                config.KEYWORD_OFFSET: "50",
                config.KEYWORD_READOUTMODE: "0",
            },
        }

        result = matching.find_matching_bias(light_metadata, bias_frames)

        assert len(result) == 1
        assert "/path/bias1.fits" in result


class TestCheckCalibrationStatus:
    """Tests for check_calibration_status function."""

    @patch("ap_move_lights_to_data.matching.get_frames_by_type")
    def test_complete_when_all_calibration_present(self, mock_get_frames):
        """Verify is_complete True when darks and flats exist with matching exposure."""
        mock_get_frames.return_value = {
            config.TYPE_LIGHT: {
                "/path/light1.fits": {
                    config.KEYWORD_TYPE: "light",
                    config.KEYWORD_CAMERA: "ASI2600MM",
                    config.KEYWORD_EXPOSURESECONDS: "300",
                    config.KEYWORD_FILTER: "Ha",
                }
            },
            config.TYPE_DARK: {
                "/path/dark1.fits": {
                    config.KEYWORD_TYPE: "dark",
                    config.KEYWORD_CAMERA: "ASI2600MM",
                    config.KEYWORD_EXPOSURESECONDS: "300",
                }
            },
            config.TYPE_FLAT: {
                "/path/flat1.fits": {
                    config.KEYWORD_TYPE: "flat",
                    config.KEYWORD_CAMERA: "ASI2600MM",
                    config.KEYWORD_FILTER: "Ha",
                }
            },
            config.TYPE_BIAS: {},
        }

        result = matching.check_calibration_status("/test/dir")

        assert result["is_complete"] is True
        assert result["has_lights"] is True
        assert result["has_darks"] is True
        assert result["has_flats"] is True
        assert result["needs_bias"] is False

    @patch("ap_move_lights_to_data.matching.get_frames_by_type")
    def test_incomplete_when_no_darks(self, mock_get_frames):
        """Verify is_complete False when no darks exist."""
        mock_get_frames.return_value = {
            config.TYPE_LIGHT: {
                "/path/light1.fits": {
                    config.KEYWORD_TYPE: "light",
                    config.KEYWORD_CAMERA: "ASI2600MM",
                }
            },
            config.TYPE_DARK: {},
            config.TYPE_FLAT: {
                "/path/flat1.fits": {
                    config.KEYWORD_TYPE: "flat",
                    config.KEYWORD_CAMERA: "ASI2600MM",
                }
            },
            config.TYPE_BIAS: {},
        }

        result = matching.check_calibration_status("/test/dir")

        assert result["is_complete"] is False
        assert result["reason"] == "No matching dark frames"

    @patch("ap_move_lights_to_data.matching.get_frames_by_type")
    def test_incomplete_when_no_flats(self, mock_get_frames):
        """Verify is_complete False when no flats exist."""
        mock_get_frames.return_value = {
            config.TYPE_LIGHT: {
                "/path/light1.fits": {
                    config.KEYWORD_TYPE: "light",
                    config.KEYWORD_CAMERA: "ASI2600MM",
                    config.KEYWORD_EXPOSURESECONDS: "300",
                }
            },
            config.TYPE_DARK: {
                "/path/dark1.fits": {
                    config.KEYWORD_TYPE: "dark",
                    config.KEYWORD_CAMERA: "ASI2600MM",
                    config.KEYWORD_EXPOSURESECONDS: "300",
                }
            },
            config.TYPE_FLAT: {},
            config.TYPE_BIAS: {},
        }

        result = matching.check_calibration_status("/test/dir")

        assert result["is_complete"] is False
        assert result["reason"] == "No matching flat frames"

    @patch("ap_move_lights_to_data.matching.get_frames_by_type")
    def test_needs_bias_when_exposure_mismatch(self, mock_get_frames):
        """Verify needs_bias True when dark exposure differs from light."""
        mock_get_frames.return_value = {
            config.TYPE_LIGHT: {
                "/path/light1.fits": {
                    config.KEYWORD_TYPE: "light",
                    config.KEYWORD_CAMERA: "ASI2600MM",
                    config.KEYWORD_EXPOSURESECONDS: "300",
                    config.KEYWORD_FILTER: "Ha",
                }
            },
            config.TYPE_DARK: {
                "/path/dark1.fits": {
                    config.KEYWORD_TYPE: "dark",
                    config.KEYWORD_CAMERA: "ASI2600MM",
                    config.KEYWORD_EXPOSURESECONDS: "120",  # Different exposure
                }
            },
            config.TYPE_FLAT: {
                "/path/flat1.fits": {
                    config.KEYWORD_TYPE: "flat",
                    config.KEYWORD_CAMERA: "ASI2600MM",
                    config.KEYWORD_FILTER: "Ha",
                }
            },
            config.TYPE_BIAS: {
                "/path/bias1.fits": {
                    config.KEYWORD_TYPE: "bias",
                    config.KEYWORD_CAMERA: "ASI2600MM",
                }
            },
        }

        result = matching.check_calibration_status("/test/dir")

        assert result["is_complete"] is True
        assert result["needs_bias"] is True
        assert result["has_bias"] is True

    @patch("ap_move_lights_to_data.matching.get_frames_by_type")
    def test_incomplete_when_needs_bias_but_none(self, mock_get_frames):
        """Verify is_complete False when bias needed but not present."""
        mock_get_frames.return_value = {
            config.TYPE_LIGHT: {
                "/path/light1.fits": {
                    config.KEYWORD_TYPE: "light",
                    config.KEYWORD_CAMERA: "ASI2600MM",
                    config.KEYWORD_EXPOSURESECONDS: "300",
                    config.KEYWORD_FILTER: "Ha",
                }
            },
            config.TYPE_DARK: {
                "/path/dark1.fits": {
                    config.KEYWORD_TYPE: "dark",
                    config.KEYWORD_CAMERA: "ASI2600MM",
                    config.KEYWORD_EXPOSURESECONDS: "120",  # Different exposure
                }
            },
            config.TYPE_FLAT: {
                "/path/flat1.fits": {
                    config.KEYWORD_TYPE: "flat",
                    config.KEYWORD_CAMERA: "ASI2600MM",
                    config.KEYWORD_FILTER: "Ha",
                }
            },
            config.TYPE_BIAS: {},  # No bias
        }

        result = matching.check_calibration_status("/test/dir")

        assert result["is_complete"] is False
        assert result["needs_bias"] is True
        assert "bias" in result["reason"].lower()

    @patch("ap_move_lights_to_data.matching.get_frames_by_type")
    def test_no_lights_found(self, mock_get_frames):
        """Verify proper handling when no light frames found."""
        mock_get_frames.return_value = {
            config.TYPE_LIGHT: {},
            config.TYPE_DARK: {},
            config.TYPE_FLAT: {},
            config.TYPE_BIAS: {},
        }

        result = matching.check_calibration_status("/test/dir")

        assert result["is_complete"] is False
        assert result["has_lights"] is False
        assert result["reason"] == "No light frames found"
